name: ${project.name}
version: ${project.version}
main: com.github.truereassembly.chattools.ChatTools
api-version: 1.13
authors: [Reassembly]
description: Control your chat with this simple plugin!
commands:
  clearchat:
    description: Clears the chat
    usage: /clearchat
    permission: chattools.clearchat
  mutechat:
    description: Mutes the chat
    usage: /mutechat
    permission: chattools.mutechat
  chattools:
    description: Gives you all the commands
    usage: /chattools
    permission: chattools
#  reloadchattools:
#    description: Reloads config
#    usage: /reloadchattools
#    permission: chattools.reload